### ISSUE TITLE
Please update sse4_crc32 version in package.json

### ISSUE THREAD

**Issue by larchwood** [Ayms/bittorrent-nodeid#1]
sse4_crc32 2.1.2 fails to install on FreeBSD. At least some version older than 5.1.0 can be installed, but don't work.
sse4_crc32 5.1.0 can be installed and passes tests.

Version for fast-crc32c should also be updated, because old fast-crc32c depend on old sse4_crc32.
Please switch to new versions.

Also I see almost no point in using both fast-crc32c and sse4_crc32, only one of the is enough:
1. fast-crc32c uses sse4_crc32 as backend.
2. sse4_crc32 has software fallback and can be used alone without fast-crc32c as intermediate layer.

**Comment by Ayms** [comment]
Right, did not spend a lot of time to optimize the modules use/usage/update, just the code

Could you please issue a PR of what you think the best combination is (keeping fast crc32 as the default)?
